name: Generate graph

on:
  push:
    branches:
      - master
  schedule:
    - cron:  '0 1 * * *'

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.8]

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        sudo apt-get install graphviz
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Compute graph
      run: |
        python src/graph.py --threads 1
    - name: Generate PDF/PNG from graph
      run: |
        mkdir _output
        cp _working_dir/graphviz.dot _output/graph.dot
        dot -Tpdf -Gdpi=300 _working_dir/graphviz.dot > _output/graph.pdf
        dot -Tpng -Gdpi=300 _working_dir/graphviz.dot > _output/graph.png
        dot -Tjson _working_dir/graphviz.dot > _output/graph.json

    - name: Upload graph-dot
      uses: actions/upload-artifact@v1
      with:
        name: graph-dot
        path: _output/graph.dot
    - name: Upload graph-pdf
      uses: actions/upload-artifact@v1
      with:
        name: graph-pdf
        path: _output/graph.pdf
    - name: Upload graph-png
      uses: actions/upload-artifact@v1
      with:
        name: graph-png
        path: _output/graph.png
    - name: Upload graph-json
      uses: actions/upload-artifact@v1
      with:
        name: graph-json
        path: _output/graph.json
    - name: Upload tapaholeslist-json
      uses: actions/upload-artifact@v1
      with:
        name: tapaholeslist-json
        path: _working_dir/tapaholeslist.json
    - name: Upload tapaholesdeps-json
      uses: actions/upload-artifact@v1
      with:
        name: tapaholesdeps-json
        path: _working_dir/tapaholesdeps.json
      
    - name: Deploy to gh-pages
      run: |
        cd _output
        echo ".nojekyll" > .nojekyll
        echo "<!doctype html><html><head></head><body><h1>Conan Center</h1>(<a href="graph.pdf">pdf</a> | <a href="graph.png">png</a>)<br/><img src=\"graph.png\"/></body></html>" > index.html
        git init .
        git checkout -b gh-pages
        git add .
        git config user.email "actions@github.com"
        git config user.name "GitHub actions"
        git commit -m "Automatic from Github actions"
        git remote add origin-pages https://jgsogo:${{ secrets.GITHUB_TOKEN }}@github.com/jgsogo/conan-center-index-graph.git > /dev/null 2>&1
        git push --quiet --force --set-upstream origin-pages gh-pages 
